language: c

script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target install
    - ctest

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake

